name: Windows

on:
  push:
    paths-ignore:
      - 'Readme.md'
    branches-ignore:
      - 'tmp*'
  pull_request:
    paths-ignore:
      - 'Readme.md'
    branches-ignore:
      - 'tmp*'

jobs:
  windows-build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, windows-2019]
        config: [Debug, Release]
        include:
            - os: windows-2022
              generator: "Visual Studio 17 2022"
            - os: windows-2019
              generator: "Visual Studio 16 2019"

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      id: cache-external
      with:
        key: ${{ matrix.os }}-${{ matrix.config }}-${{ hashFiles('external/FrameGraph/cmake/download_glfw.cmake',
                                                                 'external/FrameGraph/cmake/download_glslang.cmake',
                                                                 'external/FrameGraph/cmake/download_vk.cmake',
                                                                 'external/FrameGraph/cmake/download_vma.cmake',
                                                                 'cmake/download_spirvcross.cmake') }}
        path: |
          !**
          external/FrameGraph/external/glfw/**
          external/FrameGraph/external/glslang/**
          #external/FrameGraph/external/glslang/External/SPIRV-Tools/**
          #external/FrameGraph/external/glslang/External/SPIRV-Tools/external/SPIRV-Headers/**
          external/FrameGraph/external/Vulkan-Headers/**
          external/FrameGraph/external/VulkanMemoryAllocator/**
          external/SPIRV-Cross/**
          build/build-glslang/**
          build/lib/glslang/**
          build/build2-SPIRV-Cross/**
          build/install/SPIRV-Cross/**

    - name: Show CMake generators
      working-directory: ${{ github.workspace }}
      run: |
        cmake --version
        cmake --help
           
    - name: Configure CMake
      working-directory: ${{ github.workspace }}
      run: cmake -G "${{ matrix.generator }}" -A x64 -S . -B build 

    - name: Build
      working-directory: ${{ github.workspace }}
      run: cmake --build build --config ${{ matrix.config }}
